// MyNoteDocument.jsx
import React from "react";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: "Helvetica"
  },
  header: {
    fontSize: 20,
    marginBottom: 15,
    fontWeight: "bold",
    textAlign: "center"
  },
  section: {
    marginBottom: 12
  },
  label: {
    fontWeight: "bold"
  },
  thumbnail: {
    width: 200,
    height: 120,
    marginVertical: 10,
    borderRadius: 6,
    alignSelf: "center"
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 30,
    fontSize: 10,
    color: "grey"
  }
});

export default function MyNoteDocument({ note }) {
  return (
    <Document>
      <Page style={styles.page}>
        {/* Title */}
        <Text style={styles.header}>{note.title || "Untitled Note"}</Text>

        {/* Thumbnail */}
        {note.thumbnail && <Image src={note.thumbnail} style={styles.thumbnail} />}

        {/* Description */}
        <View style={styles.section}>
          <Text>{note.description || "No description available."}</Text>
        </View>

        {/* Class + Subject */}
        <View style={styles.section}>
          <Text>
            <Text style={styles.label}>Class: </Text>
            {note.class}
          </Text>
          <Text>
            <Text style={styles.label}>Subject: </Text>
            {note.subject}
          </Text>
        </View>

        {/* Owner */}
        <View style={styles.section}>
          <Text>
            <Text style={styles.label}>Owner: </Text>
            {note.owner?.name} ({note.owner?.username})
          </Text>
        </View>

        {/* Created Date */}
        <View style={styles.section}>
          <Text>
            <Text style={styles.label}>Created At: </Text>
            {new Date(note.createdAt).toLocaleString()}
          </Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>Generated by NotesHub</Text>
      </Page>
    </Document>
  );
}
